### ISSUE TITLE
Can this project batch process pedestrian images?

### ISSUE THREAD

**Issue by shams2023** [438443467/ComfyUI-GPT4V-Image-Captioner#2]
Can this project batch process pedestrian images? (i.e. generating corresponding text descriptions for pedestrian images)
2. Do you also need to purchase the API key for GPT4?
3. Can good captions be achieved for low resolution images?
Looking forward to your reply!
Thank you!

**Comment by 438443467** [comment]
1. GPT4V is currently the most advanced image recognition model, and I haven't seen any models that can match its accuracy. You will need to set up a batch processing image node yourself or use the "number_image" mode in my Load_Image_Batch node along with my CounterNode, which will output the corresponding image based on the number.

2. You must use the API key for GPT4, but you can also use a forwarding key from other proxy platforms.

3. As for the recognition effect of low-resolution images, you will need to try it out yourself. If you require more accurate descriptions and have unique requirements, you will need to modify the "generic_prompt" in the node code.

Translation from GPT

**Comment by shams2023** [comment]
> 1. GPT4V is currently the most advanced image recognition model, and I haven't seen any models that can match its accuracy. You will need to set up a batch processing image node yourself or use the "number_image" mode in my Load_Image_Batch node along with my CounterNode, which will output the corresponding image based on the number.
> 2. You must use the API key for GPT4, but you can also use a forwarding key from other proxy platforms.
> 3. As for the recognition effect of low-resolution images, you will need to try it out yourself. If you require more accurate descriptions and have unique requirements, you will need to modify the "generic_prompt" in the node code.
> 
> Translation from GPT

Thank you for your reply!
